# create databases
CREATE DATABASE IF NOT EXISTS `__MYSQL_DATABASE`;
CREATE DATABASE IF NOT EXISTS `__MYSQL_DATABASE_test`;

# create root user and grant rights
# CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY '__MYSQL_ROOT_PASSWORD';
CREATE USER IF NOT EXISTS '__MYSQL_USER'@'%' IDENTIFIED BY '__MYSQL_PASSWORD';

# GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON `__MYSQL_DATABASE_test`.* TO '__MYSQL_USER'@'%';
